#pragma once
// GENERATED by tools/phrases.py bake - do not hand-edit.
// Source of truth: filters/phrases.json in df2-workstation (the Workstation
// edits that). AUDITION BAKE 2026-08-09 (Tyson: "Go"): ALL 56 E-mu Function
// Generator patterns selectable, the six earlier-curated first (their names
// are on probation - winners get named AFTER the listening), the remaining
// fifty under their original E-mu source names. Values are bipolar,
// peak-normalised to 1.0 per phrase - DEPTH is the travel dial.
namespace trench
{
struct FuncGenPattern
{
    const char* name;
    int   steps;        // playable steps (End Step + 1)
    int   direction;    // 0 fwd, 1 rev, 2 pendulum, 3 random, 4 brownian, 5 one-shot
    bool  smooth;       // linear interpolation between steps
    const float* values;    // steps entries, bipolar, peak-normalised
    const unsigned char* trigs; // authored accent cells (unused in v1)
};
inline constexpr float kFgV0[] = { 0.881356f, -0.830508f, 0.000000f, -0.864407f, 1.000000f, -0.423729f, 0.000000f, -0.745763f, 0.949153f, -0.779661f, -0.016949f, -0.593220f, 0.677966f, -0.711864f, 0.830508f, -0.474576f };
inline constexpr unsigned char kFgT0[] = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0 };
inline constexpr float kFgV1[] = { 0.796296f, 0.518519f, 0.296296f, 0.888889f, 0.537037f, 0.259259f, 1.000000f, 0.462963f, 0.870370f, 0.629630f, 0.425926f, 0.981481f, 0.648148f, 0.259259f, 0.777778f, 0.129630f };
inline constexpr unsigned char kFgT1[] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV2[] = { 0.000000f, -0.500000f, 0.000000f, 1.000000f, -0.500000f, 0.000000f, 0.500000f, -1.000000f, 1.000000f, 0.000000f, 0.500000f, -0.500000f, -1.000000f, 0.000000f, -1.000000f, 0.500000f, -0.500000f, 0.000000f, 1.000000f, 0.000000f, -0.500000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 1.000000f, -1.000000f, 0.500000f, 0.000000f, -0.500000f, -1.000000f, 0.000000f, -0.500000f, 1.000000f, 0.000000f, -1.000000f, 1.000000f, -0.500000f, 0.000000f, 0.500000f, -1.000000f, 0.500000f, -0.500000f, 0.000000f, 1.000000f, 0.500000f, -0.500000f, 0.000000f, -0.520833f, -1.000000f, 0.500000f, -1.000000f, 1.000000f, -0.500000f, 0.000000f, 0.500000f, -1.000000f, 1.000000f, 0.000000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 0.500000f };
inline constexpr unsigned char kFgT2[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV3[] = { 1.000000f, -1.000000f, 0.916667f, -0.916667f, 0.833333f, -0.833333f, 0.750000f, -0.750000f, 0.666667f, -0.666667f, 0.583333f, -0.583333f, 0.500000f, -0.500000f, 0.416667f, -0.416667f, 0.333333f, -0.333333f, 0.250000f, -0.250000f, 0.166667f, -0.166667f, 0.083333f, -0.083333f };
inline constexpr unsigned char kFgT3[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV4[] = { -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, -1.000000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT4[] = { 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0 };
inline constexpr float kFgV5[] = { 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.041667f, 0.104167f, 0.187500f, 0.250000f, 0.333333f, 0.458333f, 0.604167f, 0.770833f, 0.916667f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f };
inline constexpr unsigned char kFgT5[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV6[] = { 0.000000f, 0.225806f, 0.387097f, 0.225806f, 0.387097f, 0.612903f, 0.387097f, 0.612903f, 0.774194f, 0.612903f, 0.774194f, 1.000000f };
inline constexpr unsigned char kFgT6[] = { 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1 };
inline constexpr float kFgV7[] = { 0.000000f, 0.291667f, 0.500000f, 0.291667f, 0.500000f, 0.791667f, 1.000000f, 0.791667f };
inline constexpr unsigned char kFgT7[] = { 1, 1, 1, 1, 1, 1, 1, 0 };
inline constexpr float kFgV8[] = { 0.000000f, 0.583333f, 1.000000f, 0.583333f };
inline constexpr unsigned char kFgT8[] = { 1, 0, 1, 0 };
inline constexpr float kFgV9[] = { 0.062500f, -1.000000f, -0.171875f, -1.000000f, -0.187500f, -1.000000f, 0.062500f, -0.265625f, -1.000000f, -0.203125f, -1.000000f, -0.250000f };
inline constexpr unsigned char kFgT9[] = { 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1 };
inline constexpr float kFgV10[] = { 0.000000f, 0.000000f, -0.222222f, -0.333333f, -0.555556f, -0.555556f, -0.333333f, -0.222222f, 0.000000f, 0.000000f, -0.222222f, -0.333333f, -0.555556f, -0.555556f, -1.000000f, -0.777778f };
inline constexpr unsigned char kFgT10[] = { 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV11[] = { -1.000000f, 0.000000f, 1.000000f, 0.000000f, 1.000000f, 0.000000f, -0.750000f, 0.000000f };
inline constexpr unsigned char kFgT11[] = { 1, 0, 1, 0, 1, 0, 1, 0 };
inline constexpr float kFgV12[] = { 0.000000f, 0.250000f, 0.416667f, 0.500000f, 0.583333f, 0.250000f, 0.000000f, -0.166667f, 0.000000f, 0.000000f, -1.000000f, 0.000000f, 1.000000f, 0.000000f, -0.166667f, 0.000000f };
inline constexpr unsigned char kFgT12[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0 };
inline constexpr float kFgV13[] = { 0.000000f, -0.200000f, -0.400000f, -0.600000f, 0.200000f, 0.000000f, -0.200000f, -0.400000f, 0.400000f, 0.200000f, 0.000000f, -0.200000f, 0.600000f, 0.400000f, 0.200000f, 0.000000f, 0.800000f, 0.600000f, 0.400000f, 0.200000f, 1.000000f, 0.800000f, 0.600000f, 0.400000f };
inline constexpr unsigned char kFgT13[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV14[] = { 0.000000f, 0.090909f, 0.181818f, 0.272727f, 0.363636f, 0.454545f, 0.545455f, 0.636364f, 0.727273f, 0.818182f, 0.909091f, 1.000000f };
inline constexpr unsigned char kFgT14[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV15[] = { -0.705882f, 0.411765f, 0.705882f, 0.411765f, 0.235294f, 0.411765f, -0.411765f, 0.529412f, 0.705882f, 0.529412f, 1.000000f, 0.470588f, -0.294118f, 0.411765f, 0.705882f, 0.411765f, 0.823529f, 0.411765f, -0.411765f, 0.294118f, 0.529412f, -0.411765f, 0.000000f, 0.294118f };
inline constexpr unsigned char kFgT15[] = { 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0 };
inline constexpr float kFgV16[] = { 0.000000f, 0.428571f, 0.714286f, 0.428571f, 0.285714f, -0.285714f, -0.285714f, 0.714286f, 0.714286f, -1.000000f, 0.285714f, 0.428571f, 0.000000f, -0.285714f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT16[] = { 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1 };
inline constexpr float kFgV17[] = { 0.000000f, 0.263158f, 0.526316f, 0.157895f, 0.421053f, 0.684211f, 0.315789f, 0.578947f, 0.842105f, 0.473684f, 0.736842f, 1.000000f };
inline constexpr unsigned char kFgT17[] = { 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0 };
inline constexpr float kFgV18[] = { 0.000000f, 0.416667f, 0.500000f, -0.083333f, 0.500000f, 0.916667f, 1.000000f, 0.416667f };
inline constexpr unsigned char kFgT18[] = { 1, 0, 0, 1, 0, 0, 0, 1 };
inline constexpr float kFgV19[] = { 0.000000f, 0.833333f, 1.000000f, -0.166667f };
inline constexpr unsigned char kFgT19[] = { 1, 0, 1, 0 };
inline constexpr float kFgV20[] = { 0.000000f, 0.000000f, -0.400000f, 0.600000f, 0.600000f, 0.000000f, -1.000000f, -1.000000f, -1.000000f, -0.400000f, 0.000000f, -0.400000f, 0.600000f, 0.600000f, 0.000000f, -0.400000f };
inline constexpr unsigned char kFgT20[] = { 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1 };
inline constexpr float kFgV21[] = { 0.000000f, 0.500000f, -0.083333f, 0.500000f, 1.000000f, 0.500000f, 0.000000f, 0.500000f, 0.625000f, -0.083333f, 0.000000f, -0.083333f, 1.000000f, 0.416667f, 0.000000f, -0.083333f };
inline constexpr unsigned char kFgT21[] = { 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1 };
inline constexpr float kFgV22[] = { 1.000000f, -1.000000f, 0.500000f, -0.500000f, 0.250000f, -0.250000f, 0.125000f, -0.125000f };
inline constexpr unsigned char kFgT22[] = { 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV23[] = { 0.000000f, 0.062500f, 0.125000f, 0.171875f, 0.218750f, 0.265625f, 0.343750f, 0.437500f, 0.531250f, 0.625000f, 0.734375f, 0.859375f, 1.000000f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, 1.000000f, 1.000000f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, 0.968750f, 0.968750f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, 0.906250f, 0.906250f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, 0.859375f, -1.000000f, -1.000000f, -1.000000f, 0.812500f, -1.000000f, -1.000000f, 0.703125f, -1.000000f, 0.578125f, -1.000000f, 0.234375f, -1.000000f, 0.078125f, -1.000000f, 0.140625f, -1.000000f, 0.234375f, -1.000000f, 0.343750f, -1.000000f, 0.484375f, -1.000000f, 0.718750f, -1.000000f, 0.468750f };
inline constexpr unsigned char kFgT23[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV24[] = { -0.111111f, -0.222222f, 0.666667f, 0.222222f, -0.222222f, -0.444444f, 0.000000f, 0.111111f, 0.777778f, 0.333333f, -0.555556f, 0.222222f, -0.444444f, -0.333333f, -0.666667f, 0.444444f, -0.333333f, -0.444444f, 0.444444f, -0.666667f, -0.222222f, -0.666667f, 0.555556f, -0.333333f, -0.555556f, 0.333333f, -0.222222f, -0.333333f, 0.444444f, -1.000000f, 0.444444f, -0.555556f, 0.000000f, 0.222222f, -0.111111f, -0.444444f, -0.222222f, 0.333333f, -0.555556f, -0.333333f, -0.111111f, 0.259259f, 0.444444f, -0.222222f, 0.333333f, -0.333333f, 0.111111f, -0.333333f, -0.333333f, -0.222222f, 0.222222f, -0.222222f, 0.111111f, -0.222222f, 0.444444f, 0.333333f, -0.333333f, -0.555556f, 0.333333f, -0.333333f, -0.333333f, -0.777778f, 0.333333f, -0.333333f };
inline constexpr unsigned char kFgT24[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV25[] = { 0.000000f, 0.000000f, -0.166667f, 0.000000f, -1.000000f, -1.000000f, -0.750000f, -0.583333f };
inline constexpr unsigned char kFgT25[] = { 1, 0, 1, 0, 1, 1, 1, 1 };
inline constexpr float kFgV26[] = { 0.000000f, 0.583333f, 1.000000f, -0.166667f, 0.000000f, -0.166667f, 0.000000f, 0.083333f, 0.000000f, 0.000000f, -0.166667f, 0.000000f, 0.000000f, -0.166667f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT26[] = { 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0 };
inline constexpr float kFgV27[] = { 0.000000f, 0.583333f, 1.000000f, -0.166667f, 0.000000f, -0.166667f, 0.000000f, -1.000000f, 0.000000f, 1.000000f, -0.166667f, 0.000000f, 0.000000f, -0.166667f, -0.166667f, 0.583333f };
inline constexpr unsigned char kFgT27[] = { 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1 };
inline constexpr float kFgV28[] = { 0.000000f, -0.166667f, 0.250000f, 0.000000f, 0.000000f, -0.166667f, 0.000000f, -1.000000f, 0.000000f, 1.000000f, -0.166667f, 0.000000f, 0.000000f, -0.166667f, -0.166667f, 0.583333f };
inline constexpr unsigned char kFgT28[] = { 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1 };
inline constexpr float kFgV29[] = { 0.000000f, 0.166667f, 0.291667f, 0.500000f, 0.666667f, 0.791667f, 1.000000f, 0.791667f, 0.666667f, 0.500000f, 0.291667f, 0.166667f, 0.000000f, -0.208333f, -0.333333f, -0.500000f, -0.708333f, -0.833333f, -1.000000f, -0.833333f, -0.708333f, -0.500000f, -0.333333f, -0.208333f };
inline constexpr unsigned char kFgT29[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV30[] = { 0.000000f, 0.166667f, 0.333333f, 0.416667f, 0.583333f, 0.750000f, 0.916667f, 1.000000f };
inline constexpr unsigned char kFgT30[] = { 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV31[] = { 0.000000f, -1.000000f, -0.400000f, -0.400000f, -1.000000f, -0.400000f, 0.000000f, -0.600000f, 0.000000f, 0.400000f, 0.600000f, -0.400000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT31[] = { 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1 };
inline constexpr float kFgV32[] = { 0.000000f, 0.000000f, 0.600000f, -0.400000f, 0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, -0.400000f, 0.600000f, 0.000000f, -1.000000f };
inline constexpr unsigned char kFgT32[] = { 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0 };
inline constexpr float kFgV33[] = { 0.000000f, 0.145833f, 0.291667f, 0.500000f, 0.645833f, 0.791667f, 1.000000f, 0.791667f, 0.645833f, 0.500000f, 0.291667f, 0.145833f, 0.000000f, -0.208333f, -0.375000f, -0.500000f, -0.708333f, -0.875000f, -1.000000f, -0.875000f, -0.708333f, -0.500000f, -0.375000f, -0.208333f };
inline constexpr unsigned char kFgT33[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV34[] = { 0.000000f, 0.166667f, 0.250000f, 0.416667f, 0.583333f, 0.750000f, 0.833333f, 1.000000f };
inline constexpr unsigned char kFgT34[] = { 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV35[] = { 0.000000f, -0.400000f, 0.400000f, -0.600000f, 0.600000f, 0.600000f, -1.000000f, -1.000000f };
inline constexpr unsigned char kFgT35[] = { 1, 0, 0, 1, 0, 0, 1, 0 };
inline constexpr float kFgV36[] = { 0.612903f, 0.000000f, 0.790323f, -0.016129f, 0.983871f, -0.016129f, -0.016129f, 0.854839f, -0.016129f, 0.161290f, 0.338710f, 0.677419f, 0.000000f, 0.322581f, 0.661290f, 0.161290f, 1.000000f, 0.774194f, 0.516129f, 0.209677f, -0.016129f, 0.741935f, 0.451613f, 0.919355f };
inline constexpr unsigned char kFgT36[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV37[] = { 0.000000f, -0.090909f, 0.181818f, -0.272727f, 0.363636f, 0.363636f, -0.454545f, -0.454545f, 0.545455f, 0.545455f, -0.636364f, -0.636364f, 0.727273f, 0.727273f, 0.727273f, -0.818182f, -0.818182f, -0.818182f, 0.909091f, 0.909091f, 0.909091f, -1.000000f, -1.000000f, -1.000000f };
inline constexpr unsigned char kFgT37[] = { 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1 };
inline constexpr float kFgV38[] = { 0.000000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 1.000000f, -1.000000f, -1.000000f, -1.000000f, -1.000000f, 0.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f };
inline constexpr unsigned char kFgT38[] = { 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1 };
inline constexpr float kFgV39[] = { 0.000000f, 0.500000f, -0.500000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, -0.500000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.500000f, -0.500000f, 0.000000f, -0.291667f };
inline constexpr unsigned char kFgT39[] = { 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0 };
inline constexpr float kFgV40[] = { 0.000000f, 0.466667f, 0.800000f, 0.000000f, 0.466667f, 0.800000f, 0.000000f, 0.466667f, 1.000000f, 0.000000f, 0.466667f, 0.933333f, 0.000000f, 0.466667f, 0.800000f, 0.466667f, 0.000000f, 0.466667f, 0.800000f, 0.000000f, 0.466667f, 0.800000f, 0.000000f, 0.466667f, 1.000000f, 0.000000f, 0.466667f, 0.933333f, 0.000000f, 0.466667f, 0.800000f, 0.466667f };
inline constexpr unsigned char kFgT40[] = { 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0 };
inline constexpr float kFgV41[] = { 0.000000f, -0.612903f, 0.483871f, 0.387097f, -1.000000f, 0.322581f, -0.161290f, -0.677419f, 0.387097f, -0.774194f, 0.612903f, -0.225806f, 0.000000f, 0.709677f, -0.161290f, -0.548387f };
inline constexpr unsigned char kFgT41[] = { 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1 };
inline constexpr float kFgV42[] = { 0.000000f, -0.291667f, 0.125000f, 0.625000f, -0.375000f, 0.416667f, -0.208333f, -0.083333f, 0.500000f, -1.000000f, 0.791667f, -0.291667f, 0.000000f, -0.083333f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT42[] = { 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0 };
inline constexpr float kFgV43[] = { 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT43[] = { 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV44[] = { 0.000000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT44[] = { 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV45[] = { 0.000000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT45[] = { 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV46[] = { 0.000000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT46[] = { 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV47[] = { 0.000000f, 0.000000f, 0.600000f, 0.000000f, 0.600000f, 0.000000f, -0.400000f, 0.000000f, 0.000000f, 0.000000f, 0.600000f, 0.000000f, -0.400000f, -1.000000f, -0.400000f, 0.000000f };
inline constexpr unsigned char kFgT47[] = { 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0 };
inline constexpr float kFgV48[] = { 0.000000f, 0.172414f, 0.241379f, 0.413793f, 0.586207f, 0.655172f, 0.827586f, 1.000000f };
inline constexpr unsigned char kFgT48[] = { 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV49[] = { 0.000000f, -0.166667f, 0.166667f, -0.333333f, 0.250000f, 0.250000f, -0.416667f, -0.416667f, 0.416667f, 0.416667f, -0.583333f, -0.583333f, -0.583333f, 0.583333f, 0.583333f, 0.583333f, -0.750000f, -0.750000f, -0.750000f, -0.750000f, 0.666667f, 0.666667f, 0.666667f, -0.833333f, -0.833333f, -0.833333f, 0.833333f, 0.833333f, -1.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT49[] = { 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1 };
inline constexpr float kFgV50[] = { 1.000000f, -1.000000f, 0.984375f, -0.937500f, 0.937500f, -0.875000f, 0.859375f, -0.812500f, 0.796875f, -0.734375f, 0.687500f, -0.656250f, 0.640625f, -0.578125f, 0.562500f, -0.484375f, 0.468750f, -0.390625f, 0.406250f, -0.328125f, 0.343750f, -0.265625f, 0.296875f, -0.218750f, 0.234375f, -0.156250f, 0.140625f, -0.109375f, 0.171875f, -0.140625f, 0.203125f, -0.218750f, 0.250000f, -0.171875f, 0.187500f, -0.140625f, 0.109375f, -0.171875f, 0.171875f, -0.234375f, 0.234375f, -0.296875f, 0.312500f, -0.359375f, 0.390625f, -0.437500f, 0.468750f, -0.500000f, 0.531250f, -0.562500f, 0.593750f, -0.625000f, 0.656250f, -0.687500f, 0.734375f, -0.734375f, 0.828125f, -0.796875f, 0.906250f, -0.890625f, 0.968750f, -0.953125f, 1.000000f, -1.000000f };
inline constexpr unsigned char kFgT50[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV51[] = { 1.000000f, -1.000000f, 0.000000f, 1.000000f, -1.000000f, -0.015625f, 1.000000f, -1.000000f, 1.000000f, -1.000000f, 1.000000f, -1.000000f, -0.015625f, 1.000000f, -1.000000f, 0.000000f, 1.000000f, -0.781250f, 0.828125f, -0.546875f, 0.500000f, -1.000000f, 1.000000f, -0.906250f, 0.875000f, -0.656250f, 0.703125f, -0.328125f, 0.500000f, 0.000000f, 0.296875f, 0.656250f };
inline constexpr unsigned char kFgT51[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV52[] = { 0.000000f, -1.000000f, 0.000000f, -1.000000f, 0.000000f, -0.984375f, 0.000000f, -0.968750f, 0.000000f, -1.000000f, 0.000000f, -0.953125f, 0.000000f, -0.953125f, 0.000000f, -0.984375f };
inline constexpr unsigned char kFgT52[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV53[] = { 0.000000f, -0.546875f, -0.875000f, -0.015625f, -0.546875f, -0.031250f, -0.031250f, -0.187500f, -0.015625f, -0.921875f, -0.031250f, -0.906250f, -0.031250f, -0.890625f, -0.140625f, -1.000000f };
inline constexpr unsigned char kFgT53[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV54[] = { -0.020833f, -0.083333f, -0.104167f, -0.166667f, 0.083333f, 0.125000f, 0.145833f, -0.250000f, 0.208333f, -0.229167f, 0.666667f, -0.583333f, 0.708333f, -0.666667f, 1.000000f, -1.000000f };
inline constexpr unsigned char kFgT54[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV55[] = { 0.000000f, 0.000000f, 0.428571f, 0.000000f, 0.428571f, 0.000000f, -0.285714f, 0.000000f, 0.000000f, 0.000000f, 0.428571f, 0.000000f, -0.285714f, -0.714286f, -0.285714f, 0.000000f, 1.000000f, -0.714286f, 0.714286f, 0.428571f, 0.000000f, -0.714286f, -0.714286f, 1.000000f, -0.714286f, 0.714286f, 0.428571f, 0.000000f, -0.285714f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT55[] = { 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1 };
inline constexpr FuncGenPattern kFuncGenPatterns[] = {
    { "BREATHE", 16, 0, true, kFgV0, kFgT0 },
    { "RHYTHM", 16, 0, false, kFgV1, kFgT1 },
    { "WANDER", 64, 4, false, kFgV2, kFgT2 },
    { "ANSWER", 24, 2, false, kFgV3, kFgT3 },
    { "STABS", 16, 0, false, kFgV4, kFgT4 },
    { "RISE", 64, 5, true, kFgV5, kFgT5 },
    { "5th + Oct - Extended Alt", 12, 2, false, kFgV6, kFgT6 },
    { "5th + Oct - Extended", 8, 0, false, kFgV7, kFgT7 },
    { "5th + Oct", 4, 0, false, kFgV8, kFgT8 },
    { "Cuban", 12, 0, false, kFgV9, kFgT9 },
    { "Another Riff", 16, 0, false, kFgV10, kFgT10 },
    { "Another Time", 8, 0, false, kFgV11, kFgT11 },
    { "Blue View", 16, 2, false, kFgV12, kFgT12 },
    { "Cascading", 24, 0, false, kFgV13, kFgT13 },
    { "Chromatic", 12, 2, false, kFgV14, kFgT14 },
    { "Diddy 1", 24, 0, false, kFgV15, kFgT15 },
    { "Diddy 2", 16, 1, false, kFgV16, kFgT16 },
    { "Diminishing Return", 12, 2, false, kFgV17, kFgT17 },
    { "Flat 7 + Oct - Extended", 8, 0, false, kFgV18, kFgT18 },
    { "Flat 7 + Oct", 4, 0, false, kFgV19, kFgT19 },
    { "Funky Machine 1", 16, 0, false, kFgV20, kFgT20 },
    { "Funky Machine 2", 16, 0, false, kFgV21, kFgT21 },
    { "Half the size each step", 8, 1, false, kFgV22, kFgT22 },
    { "HorseLaugh", 64, 0, true, kFgV23, kFgT23 },
    { "Jittery", 64, 2, true, kFgV24, kFgT24 },
    { "Little Riff", 8, 2, false, kFgV25, kFgT25 },
    { "Mach Groove 1", 16, 0, false, kFgV26, kFgT26 },
    { "Mach Groove 2", 16, 0, false, kFgV27, kFgT27 },
    { "Mach Groove 3", 16, 0, false, kFgV28, kFgT28 },
    { "Major Arp", 24, 0, false, kFgV29, kFgT29 },
    { "Major Scale", 8, 2, false, kFgV30, kFgT30 },
    { "Melodic Frenzy", 16, 2, false, kFgV31, kFgT31 },
    { "Melodic Madness", 16, 0, false, kFgV32, kFgT32 },
    { "Minor Arp", 24, 0, false, kFgV33, kFgT33 },
    { "Minor Scale", 8, 2, false, kFgV34, kFgT34 },
    { "Skirmish - Minor", 8, 1, false, kFgV35, kFgT35 },
    { "MorseCode24FUN", 24, 0, false, kFgV36, kFgT36 },
    { "1 Oct Random - Chromatic", 24, 3, false, kFgV37, kFgT37 },
    { "Octave Jumper", 16, 0, false, kFgV38, kFgT38 },
    { "Octavious", 16, 0, false, kFgV39, kFgT39 },
    { "Oddigy Arpeggio", 32, 0, false, kFgV40, kFgT40 },
    { "Pentatonic Play 1", 16, 0, false, kFgV41, kFgT41 },
    { "Pentatonic Play 2", 16, 0, false, kFgV42, kFgT42 },
    { "Phrase 0", 8, 5, false, kFgV43, kFgT43 },
    { "Phrase 1 Shot 1", 8, 5, false, kFgV44, kFgT44 },
    { "Phrase 2", 8, 1, false, kFgV45, kFgT45 },
    { "Phrase 3", 6, 2, false, kFgV46, kFgT46 },
    { "ProgRocker", 16, 2, false, kFgV47, kFgT47 },
    { "QuartalArpeggios", 8, 2, false, kFgV48, kFgT48 },
    { "Funky Random Minor", 33, 3, false, kFgV49, kFgT49 },
    { "StepSweeper64FUN", 64, 0, false, kFgV50, kFgT50 },
    { "Syncopatico32FUN", 32, 0, true, kFgV51, kFgT51 },
    { "The Editor", 16, 0, false, kFgV52, kFgT52 },
    { "The Editor 2", 16, 0, false, kFgV53, kFgT53 },
    { "The Editor 3", 16, 0, false, kFgV54, kFgT54 },
    { "WayProgger", 32, 0, false, kFgV55, kFgT55 },
};
inline constexpr int kNumFuncGenPatterns = 56;
}
