[package]
name = "trench-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trench"
path = "src/main.rs"

[dependencies]
trench-core = { path = "../trench-core" }
author = { path = "../author" }
author-server = { path = "../author-server" }
eframe = "0.36.1"
egui = "0.36.1"
egui-wgpu = "0.36.1"
wgpu = "30"
cpal = "0.18.2"

[features]
inspection = ["eframe/inspection"]

[dev-dependencies]
egui_kittest = { version = "0.36.1", features = ["wgpu", "snapshot", "eframe"] }
