#pragma once
// GENERATED by tools/bake_original_funcgens.py - do not hand-edit.
// Source: filters/original_patterns.json (SHA-256 8713e4a7e1d171213a19a836dfa8ca4d168b54cbcb2354197cebac1d663641ce)
// Provenance: Independently authored for TRENCH on 2026-08-27
namespace trench
{
struct FuncGenPattern
{
    const char* name;
    int steps;
    int direction;
    bool smooth;
    const float* values;
    const unsigned char* trigs;
    double stepBeats;
    double rateHz;
};
inline constexpr float kFgV0[] = { 0.000000000f, -1.000000000f, 0.000000000f, 0.750000000f, 0.000000000f, -0.500000000f, 0.250000000f, 1.000000000f, 0.000000000f, -0.250000000f, 0.500000000f, 0.000000000f, -0.750000000f, 0.000000000f, 1.000000000f, -0.500000000f };
inline constexpr unsigned char kFgT0[] = { 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0 };
inline constexpr float kFgV1[] = { -0.800000000f, -0.350000000f, 0.100000000f, 0.650000000f, -0.550000000f, -0.100000000f, 0.450000000f, 1.000000000f, -1.000000000f, -0.400000000f, 0.200000000f, 0.750000000f, -0.650000000f, -0.150000000f, 0.350000000f, 0.850000000f };
inline constexpr unsigned char kFgT1[] = { 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1 };
inline constexpr float kFgV2[] = { -1.000000000f, 0.200000000f, 0.650000000f, -0.450000000f, 0.800000000f, 0.050000000f, -0.700000000f, 0.450000000f, 1.000000000f, -0.250000000f, 0.550000000f, -0.850000000f };
inline constexpr unsigned char kFgT2[] = { 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0 };
inline constexpr float kFgV3[] = { -1.000000000f, -0.600000000f, -0.100000000f, 0.450000000f, 1.000000000f, 0.550000000f, 0.050000000f, -0.500000000f };
inline constexpr unsigned char kFgT3[] = { 1, 0, 0, 0, 1, 0, 0, 0 };
inline constexpr float kFgV4[] = { -1.000000000f, -0.700000000f, -0.150000000f, 0.500000000f, 1.000000000f, 0.600000000f, 0.000000000f, -0.550000000f };
inline constexpr unsigned char kFgT4[] = { 1, 0, 0, 0, 1, 0, 0, 0 };
inline constexpr float kFgV5[] = { -1.000000000f, -0.400000000f, 0.300000000f, -0.750000000f, 0.000000000f, 0.700000000f, -0.200000000f, 1.000000000f, 0.450000000f, -0.550000000f, 0.150000000f, 0.850000000f };
inline constexpr unsigned char kFgT5[] = { 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0 };
inline constexpr float kFgV6[] = { -1.000000000f, 0.350000000f, -0.600000000f, 0.750000000f, -0.150000000f, 1.000000000f, 0.200000000f, -0.800000000f };
inline constexpr unsigned char kFgT6[] = { 1, 0, 1, 0, 1, 0, 1, 0 };
inline constexpr float kFgV7[] = { -1.000000000f, -0.900000000f, -0.750000000f, -0.550000000f, -0.300000000f, 0.000000000f, 0.350000000f, 0.650000000f, 1.000000000f, 0.800000000f, 0.550000000f, 0.300000000f, 0.100000000f, -0.050000000f, -0.150000000f, 0.000000000f };
inline constexpr unsigned char kFgT7[] = { 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0 };
inline constexpr FuncGenPattern kFuncGenPatterns[] = {
    { "Rail Switch", 16, 0, false, kFgV0, kFgT0, 0.25, 0.0 },
    { "Backbeat Bloom", 16, 0, true, kFgV1, kFgT1, 0.25, 0.0 },
    { "Triplet Relay", 12, 0, false, kFgV2, kFgT2, 0.16666666666666666, 0.0 },
    { "Eighth Sway", 8, 2, true, kFgV3, kFgT3, 0.5, 0.0 },
    { "Quarter Arc", 8, 0, true, kFgV4, kFgT4, 1.0, 0.0 },
    { "Broken Ladder", 12, 1, false, kFgV5, kFgT5, 0.5, 0.0 },
    { "Pendulum Teeth", 8, 2, false, kFgV6, kFgT6, 1.0, 0.0 },
    { "Long Return", 16, 5, true, kFgV7, kFgT7, 0.25, 0.0 },
};
inline constexpr int kNumFuncGenPatterns = 8;
}
