[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trench-editor"
path = "src/main.rs"

[dependencies]
trench-core = { path = "../trench-core" }
author = { path = "../author" }
eframe = "0.29"
cpal = "0.15"
serde_json = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
