#!/usr/bin/env python3
import sys, re, unicodedata
from pathlib import Path
from xml.etree import ElementTree

SRC = Path(r"C:\Users\hooki\OneDrive\Documents\Creative Professional\Emulator X Family\Templates\Function Generator")
OUT = Path(__file__).resolve().parent.parent / "plugin" / "source" / "dsp" / "FuncGenPatterns.h"

def parse(path):
    root = ElementTree.parse(path).getroot()
    name = root.get("name").strip()
    get = lambda tag: root.find(tag)
    num = lambda tag, cast=float: cast(get(tag).text.strip())
    values = [0.0] * 64
    trigs = [0] * 64
    for v in root.findall("value"):
        values[int(v.get("index"))] = float(v.text.strip())
    for t in root.findall("trigger"):
        trigs[int(t.get("index"))] = int(t.text.strip())
    return {
        "name": name,
        "bpm": num("bpm", int),
        "rate": num("rate"),
        "smooth": num("smooth", int),
        "direction": num("direction", int),
        "steps": num("length", int) + 1,
        "values": values,
        "trigs": trigs,
    }

SHIP = {
    "16StepShaker":     "BREATHE",
    "EightEightRhythm": "RHYTHM",
    "UpToPitchFUN":     "RISE",
    "OctaveBrownFUN":   "WANDER",
    "Shark Tooth":      "ANSWER",
    "Simple Boogaloo":  "STABS",
}

def main():
    pats = []
    for f in sorted(SRC.glob("*.xml")):
        p = parse(f)
        if p["name"] not in SHIP:
            continue
        p["name"] = SHIP[p["name"]]
        vals = p["values"][: p["steps"]]
        peak = max(abs(v) for v in vals) if vals else 0.0
        if peak < 1e-6:
            print(f"skip (no travel): {p['name']}")
            continue
        p["values"] = [v / peak for v in vals]
        p["trigs"] = p["trigs"][: p["steps"]]
        pats.append(p)

    lines = []
    w = lines.append
    w("#pragma once")
    w("// GENERATED by tools/bake_funcgen_patterns.py - do not hand-edit.")
    w("// Emulator X factory Function Generator templates, values normalised to")
    w("// peak 1.0 per pattern (DEPTH is the travel dial). Authored data is law.")
    w("namespace trench")
    w("{")
    w("struct FuncGenPattern")
    w("{")
    w("    const char* name;")
    w("    int   steps;        // playable steps (End Step + 1)")
    w("    int   direction;    // 0 fwd, 1 rev, 2 pendulum, 3 random, 4 brownian, 5 one-shot")
    w("    bool  smooth;       // linear interpolation between steps")
    w("    const float* values;    // steps entries, bipolar, peak-normalised")
    w("    const unsigned char* trigs; // authored accent cells (unused in v1)")
    w("};")
    for i, p in enumerate(pats):
        vals = ", ".join(f"{v:.6f}f" for v in p["values"])
        trigs = ", ".join(str(t) for t in p["trigs"])
        w(f"inline constexpr float kFgV{i}[] = {{ {vals} }};")
        w(f"inline constexpr unsigned char kFgT{i}[] = {{ {trigs} }};")
    w("inline constexpr FuncGenPattern kFuncGenPatterns[] = {")
    for i, p in enumerate(pats):
        nm = p["name"].replace('"', '\\"')
        w(f'    {{ "{nm}", {p["steps"]}, {p["direction"]}, {"true" if p["smooth"] else "false"}, kFgV{i}, kFgT{i} }},')
    w("};")
    w(f"inline constexpr int kNumFuncGenPatterns = {len(pats)};")
    w("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"baked {len(pats)} patterns -> {OUT}")

if __name__ == "__main__":
    main()
