"""Bake dev/curves/*.curve.json into the plugin's compiled lookup tables.

Every macro the processor reads passes through a table generated here. A
bisection session writes knob->internal points; this samples a monotone cubic
(Fritsch-Carlson) through them at 129 points. An axis with no session keeps
the identity table, so the shipping engine is unchanged until someone sits
down and listens.
"""

from __future__ import annotations

import json
import pathlib
import sys

AXES = ("morph", "q", "bite", "follow", "mix", "slam", "preamp", "track")
SAMPLES = 129

ROOT = pathlib.Path(__file__).resolve().parents[2]
CURVE_DIR = ROOT / "dev" / "curves"
OUT = ROOT / "plugin" / "plugin" / "source" / "parameters" / "Curves.h"


def fritsch_carlson(xs, ys):
    n = len(xs)
    h = [xs[i + 1] - xs[i] for i in range(n - 1)]
    delta = [(ys[i + 1] - ys[i]) / h[i] for i in range(n - 1)]
    m = [0.0] * n
    m[0] = delta[0]
    m[n - 1] = delta[n - 2]
    for i in range(1, n - 1):
        if delta[i - 1] * delta[i] <= 0.0:
            m[i] = 0.0
        else:
            w1 = 2.0 * h[i] + h[i - 1]
            w2 = h[i] + 2.0 * h[i - 1]
            m[i] = (w1 + w2) / (w1 / delta[i - 1] + w2 / delta[i])
    for i in range(n - 1):
        if delta[i] == 0.0:
            m[i] = 0.0
            m[i + 1] = 0.0
    return m


def sample(xs, ys):
    m = fritsch_carlson(xs, ys)
    out = []
    for k in range(SAMPLES):
        x = k / (SAMPLES - 1)
        if x <= xs[0]:
            out.append(ys[0])
            continue
        if x >= xs[-1]:
            out.append(ys[-1])
            continue
        i = 0
        while i < len(xs) - 2 and x > xs[i + 1]:
            i += 1
        h = xs[i + 1] - xs[i]
        t = (x - xs[i]) / h
        t2 = t * t
        t3 = t2 * t
        value = (
            (2.0 * t3 - 3.0 * t2 + 1.0) * ys[i]
            + (t3 - 2.0 * t2 + t) * h * m[i]
            + (-2.0 * t3 + 3.0 * t2) * ys[i + 1]
            + (t3 - t2) * h * m[i + 1]
        )
        out.append(min(1.0, max(0.0, value)))
    return out


def table_for(files):
    stacks = []
    for path in files:
        data = json.loads(path.read_text(encoding="utf-8"))
        pairs = [(0.0, 0.0)]
        for point in data["points"]:
            pairs.append((float(point["knob"]), float(point["internal"])))
        pairs.append((1.0, 1.0))
        pairs.sort(key=lambda p: p[0])
        xs, ys = [], []
        for x, y in pairs:
            if xs and abs(x - xs[-1]) < 1e-9:
                continue
            xs.append(x)
            ys.append(y)
        stacks.append(sample(xs, ys))
    n = len(stacks)
    return [sum(s[i] for s in stacks) / n for i in range(SAMPLES)]


def literal(value):
    text = f"{value:.9g}"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text + "f"


def emit_table(name, values):
    lines = [f"inline constexpr Table {name} = {{"]
    for start in range(0, SAMPLES, 8):
        row = ", ".join(literal(v) for v in values[start:start + 8])
        lines.append("    " + row + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    sessions = {}
    if CURVE_DIR.is_dir():
        for path in sorted(CURVE_DIR.glob("*.curve.json")):
            axis = json.loads(path.read_text(encoding="utf-8"))["axis"]
            if axis not in AXES:
                print(f"skipping {path.name}: unknown axis {axis!r}", file=sys.stderr)
                continue
            sessions.setdefault(axis, []).append(path)

    identity = [k / (SAMPLES - 1) for k in range(SAMPLES)]
    body = [
        "#pragma once",
        "",
        "// GENERATED by plugin/tools/gen_curves.py from dev/curves/*.curve.json.",
        "// Do not edit by hand; rerun the generator after a bisection session.",
        "",
        "#include <array>",
        "#include <cstddef>",
        "",
        "namespace trench::curves",
        "{",
        f"inline constexpr std::size_t kTableSize = {SAMPLES};",
        "using Table = std::array<float, kTableSize>;",
        "enum class Axis { morph = 0, q, bite, follow, mix, slam, preamp, track, count };",
        "",
        emit_table("kIdentity", identity),
        "",
    ]
    for axis in AXES:
        if axis in sessions:
            body.append(emit_table(f"kCurve_{axis}", table_for(sessions[axis])))
            body.append("")
    body.append("inline constexpr std::array<const Table*, (std::size_t) Axis::count> kTables = {")
    for axis in AXES:
        name = f"kCurve_{axis}" if axis in sessions else "kIdentity"
        body.append(f"    &{name},   // {axis}")
    body.append("};")
    body.append("}")
    body.append("")

    OUT.write_text("\n".join(body), encoding="utf-8")
    measured = ", ".join(sorted(sessions)) or "none"
    print(f"{OUT.relative_to(ROOT)}: {len(AXES)} axes, measured: {measured}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
