#!/usr/bin/env python3
"""The phrase library: one JSON data file, two directions.

  import  Emulator X factory Function Generator templates -> filters/phrases.json
  bake    filters/phrases.json -> plugin/source/dsp/FuncGenPatterns.h

Why a data file: phrases used to live only as a generated C++ header with the
ship list hardcoded in this script, so authoring or renaming one meant editing
Python and rebuilding the plugin. The JSON is now the authority — the
Workstation reads and writes it live, and the header is baked from it at ship
time so the plugin stays a zero-dependency binary.

Storage grammar (unchanged, so nothing downstream moves): up to 64 cells of
bipolar float, peak-normalised to 1.0 (DEPTH is the travel dial), plus steps /
direction / smooth. The Workstation's editor draws curves INTO these cells.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from xml.etree import ElementTree

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(r"C:\Users\hooki\OneDrive\Documents\Creative Professional"
           r"\Emulator X Family\Templates\Function Generator")
JSON_PATH = ROOT / "filters" / "phrases.json"
HEADER = ROOT / "plugin" / "source" / "dsp" / "FuncGenPatterns.h"

MAX_CELLS = 64

SHIP = {
    "16StepShaker": "BREATHE",
    "EightEightRhythm": "RHYTHM",
    "UpToPitchFUN": "RISE",
    "OctaveBrownFUN": "WANDER",
    "Shark Tooth": "ANSWER",
    "Simple Boogaloo": "STABS",
}

DIRECTIONS = ["fwd", "rev", "pendulum", "random", "brownian", "one-shot"]

def parse_xml(path: Path) -> dict | None:
    root = ElementTree.parse(path).getroot()
    values = [0.0] * MAX_CELLS
    trigs = [0] * MAX_CELLS
    for v in root.findall("value"):
        values[int(v.get("index"))] = float(v.text.strip())
    for t in root.findall("trigger"):
        trigs[int(t.get("index"))] = int(t.text.strip())
    num = lambda tag, cast=float: cast(root.find(tag).text.strip())
    steps = num("length", int) + 1
    vals = values[:steps]
    peak = max((abs(v) for v in vals), default=0.0)
    if peak < 1e-6:
        return None
    src = root.get("name").strip()
    return {
        "name": SHIP.get(src, src),
        "source": src,
        "steps": steps,
        "direction": num("direction", int),
        "smooth": bool(num("smooth", int)),
        "ship": src in SHIP,
        "values": [round(v / peak, 6) for v in vals],
        "trigs": trigs[:steps],
    }

def cmd_import(args) -> None:
    if not SRC.is_dir():
        raise SystemExit(f"factory templates not found: {SRC}")
    if JSON_PATH.exists() and not args.force:
        raise SystemExit(f"{JSON_PATH} exists — pass --force to overwrite "
                         "(this discards hand-authored phrases)")
    phrases = [p for p in (parse_xml(f) for f in sorted(SRC.glob("*.xml"))) if p]
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_text(json.dumps(
        {"version": 1, "phrases": phrases}, indent=2), encoding="utf-8")
    shipped = sum(1 for p in phrases if p["ship"])
    print(f"imported {len(phrases)} phrases ({shipped} shipping) -> {JSON_PATH}")

def load() -> list[dict]:
    if not JSON_PATH.exists():
        raise SystemExit(f"{JSON_PATH} missing — run: python tools/phrases.py import")
    return json.loads(JSON_PATH.read_text(encoding="utf-8"))["phrases"]

def cmd_bake(args) -> None:
    phrases = [p for p in load() if p.get("ship")]
    if not phrases:
        raise SystemExit("no phrases flagged ship:true — nothing to bake")
    for p in phrases:
        vals = p["values"][: p["steps"]]
        peak = max((abs(v) for v in vals), default=0.0)
        if peak < 1e-6:
            raise SystemExit(f"phrase {p['name']} has no travel")
        p["values"] = [v / peak for v in vals]
        p["trigs"] = (p.get("trigs") or [0] * p["steps"])[: p["steps"]]

    w = [].append
    lines: list[str] = []
    w = lines.append
    w("#pragma once")
    w("// GENERATED by tools/phrases.py bake - do not hand-edit.")
    w("// Source of truth: filters/phrases.json (the Workstation edits that).")
    w("// Values are bipolar, peak-normalised to 1.0 per phrase — DEPTH is the")
    w("// travel dial. Authored data is law.")
    w("namespace trench")
    w("{")
    w("struct FuncGenPattern")
    w("{")
    w("    const char* name;")
    w("    int   steps;        // playable steps (End Step + 1)")
    w("    int   direction;    // 0 fwd, 1 rev, 2 pendulum, 3 random, 4 brownian, 5 one-shot")
    w("    bool  smooth;       // linear interpolation between steps")
    w("    const float* values;    // steps entries, bipolar, peak-normalised")
    w("    const unsigned char* trigs; // authored accent cells (unused in v1)")
    w("};")
    for i, p in enumerate(phrases):
        vals = ", ".join(f"{v:.6f}f" for v in p["values"])
        trigs = ", ".join(str(int(t)) for t in p["trigs"])
        w(f"inline constexpr float kFgV{i}[] = {{ {vals} }};")
        w(f"inline constexpr unsigned char kFgT{i}[] = {{ {trigs} }};")
    w("inline constexpr FuncGenPattern kFuncGenPatterns[] = {")
    for i, p in enumerate(phrases):
        nm = p["name"].replace('"', '\\"')
        w(f'    {{ "{nm}", {p["steps"]}, {int(p["direction"])}, '
          f'{"true" if p["smooth"] else "false"}, kFgV{i}, kFgT{i} }},')
    w("};")
    w(f"inline constexpr int kNumFuncGenPatterns = {len(phrases)};")
    w("}")
    HEADER.write_text("\n".join(lines) + "\n", encoding="utf-8")
    names = ", ".join(p["name"] for p in phrases)
    print(f"baked {len(phrases)} phrases -> {HEADER}\n  {names}")

def cmd_list(args) -> None:
    phrases = load()
    print(f"{'':2} {'name':20} {'source':22} {'st':>3} {'direction':>9} {'sm':>3}")
    print("-" * 64)
    for p in phrases:
        print(f"{'**' if p.get('ship') else '  '} {p['name'][:20]:20} "
              f"{p.get('source', '')[:22]:22} {p['steps']:3} "
              f"{DIRECTIONS[int(p['direction'])]:>9} {'Y' if p['smooth'] else 'n':>3}")
    print(f"\n{sum(1 for p in phrases if p.get('ship'))} shipping / {len(phrases)} total")

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    pi = sub.add_parser("import", help="factory XML -> phrases.json")
    pi.add_argument("--force", action="store_true", help="overwrite an existing phrases.json")
    pi.set_defaults(func=cmd_import)
    sub.add_parser("bake", help="phrases.json -> FuncGenPatterns.h").set_defaults(func=cmd_bake)
    sub.add_parser("list", help="show the library").set_defaults(func=cmd_list)
    args = ap.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
