function buildFigure(app,visible)
app.figure=figure('Name','TRENCH Workstation','NumberTitle','off','MenuBar','none', ...
    'ToolBar','none','Visible',visible,'Color',[.8 .8 .8],'Renderer','opengl','Theme','light', ...
    'Position',[60 50 1480 940],'Resize','off','InvertHardcopy','off', ...
    'CloseRequestFcn',@(~,~) delete(app),'WindowButtonMotionFcn',@(~,~) app.routeMouse('drag'), ...
    'WindowButtonUpFcn',@(~,~) app.routeMouse('release'));
app.nav=gobjects(1,4); names={'ANALYSE','FRAMES','MORPH','CORNER'}; rooms={'sound','frames','morph','corner'};
for k=1:4
    app.nav(k)=uicontrol(app.figure,'Style','togglebutton','String',names{k},'Tag',names{k}, ...
        'FontName','Arial','FontSize',10,'Position',[12+(k-1)*97 894 91 32], ...
        'BackgroundColor',[.886 .886 .886],'Callback',@(~,~) app.setRoom(rooms{k}));
end
app.statusText=uicontrol(app.figure,'Style','text','String','','FontName','Arial','FontSize',9, ...
    'BackgroundColor',[.8 .8 .8],'HorizontalAlignment','left','Position',[12 3 1452 23]);
app.response=trench.ui.ResponsePanel(app);
app.body=trench.ui.BodyGroup(app);
app.rooms=struct;
app.rooms.sound=trench.ui.SoundRoom(app);
app.rooms.frames=trench.ui.FramesRoom(app);
app.rooms.morph=trench.ui.MorphRoom(app);
app.rooms.corner=trench.ui.CornerRoom(app);
end
