function p = probe(app)
w=app.wordsOf; shape=trench.bridge.shapeOf(trench.bridge.decompile(w));
names={}; if ~isempty(app.bank.frames), names={app.bank.frames.name}; end
p=struct('live',app.live,'room',app.room,'corners',app.corners,'cornerNames',{app.cornerNames}, ...
    'chosen',app.chosen,'morph',app.morph,'q',app.q,'root',shape(1), ...
    'voicing',shape(2),'resonance',shape(3),'status',app.status,'playing',app.playing, ...
    'filterOn',app.filterOn,'source',app.source,'bank',struct('name',app.bank.name, ...
    'count',numel(app.bank.frames),'names',{names}),'words',w);
end
