function build(app,visible)
blue=[0 114 189]/255; gold=[196 143 0]/255; ground=[.8 .8 .8]; key=[226 226 226]/255;
app.figure=figure('Name','HEADSPACE','NumberTitle','off','MenuBar','none','ToolBar','none', ...
    'Visible',visible,'Color',ground,'Renderer','opengl','Theme','light','Position',[60 50 1480 860], ...
    'Resize','off','InvertHardcopy','off','CloseRequestFcn',@(~,~) delete(app), ...
    'WindowKeyPressFcn',@(~,e) app.onKey(e),'WindowButtonMotionFcn',@(~,~) app.onField('drag'), ...
    'WindowButtonUpFcn',@(~,~) app.onField('release'));
names={'PLAY','SAW','PINK NOISE'}; positions=[1010 790 90 32;1110 790 80 32;1200 790 170 32];
callbacks={@(s,~) app.setPlaying(logical(s.Value)),@(~,~) app.setSource('saw'),@(~,~) app.setSource('noise')};
app.keys=gobjects(1,3);
for k=1:3
    app.keys(k)=uicontrol(app.figure,'Style','togglebutton','String',names{k},'Tag',names{k},'Position',positions(k,:), ...
        'FontName','Arial','FontSize',11,'BackgroundColor',key,'Callback',callbacks{k});
end
panel=uipanel(app.figure,'Units','pixels','Position',[18 118 920 720],'BackgroundColor','w','BorderType','line');
q=app.quadrilateral; x=[min(q(:,1))-1 max(q(:,1))+1]; y=[min(q(:,2))-1 max(q(:,2))+1];
ticks=3*ceil(x(1)/3):3:3*floor(x(2)/3); yticks=3*ceil(y(1)/3):3:3*floor(y(2)/3);
app.fieldAxes=axes(panel,'Units','pixels','Position',[62 48 834 645],'Color','w','XLim',x,'YLim',y, ...
    'XDir','reverse','YDir','reverse','FontName','Arial','FontSize',10,'NextPlot','add', ...
    'PositionConstraint','innerposition','Box','off', ...
    'XTick',ticks,'XTickLabel',arrayfun(@(n) trench.bridge.noteName(n),ticks,'UniformOutput',false), ...
    'YTick',yticks,'YTickLabel',arrayfun(@(n) trench.bridge.noteName(n),yticks,'UniformOutput',false));
xlabel(app.fieldAxes,'F2'); ylabel(app.fieldAxes,'F1');
line(app.fieldAxes,q([1:4 1],1),q([1:4 1],2),'Color',[.69 .69 .69],'LineWidth',1,'HitTest','off');
app.referenceLabels=gobjects(1,numel(app.frames));
for k=1:numel(app.frames)
    app.referenceLabels(k)=text(app.fieldAxes,app.points(k,1),app.points(k,2),referenceName(app.frames(k).name), ...
        'FontName','Arial','FontSize',9,'Color',blue,'HorizontalAlignment','center', ...
        'VerticalAlignment','middle','Interpreter','tex','Clipping','on', ...
        'ButtonDownFcn',@(~,~) app.onField('press',app.points(k,:)));
end
app.arrangeReferences;
app.positionMark=line(app.fieldAxes,NaN,NaN,'Marker','s','MarkerSize',9,'MarkerFaceColor',gold, ...
    'Color',gold,'LineStyle','none','HitTest','off');
set(app.fieldAxes,'ButtonDownFcn',@(~,~) app.onField('press'));
panel=uipanel(app.figure,'Units','pixels','Position',[958 346 504 374],'BackgroundColor','w','BorderType','line');
app.liveAxes=trench.ui.draw.fixedGrid(panel,[49 40 432 288]);
app.liveCurve=trench.ui.draw.responseCurve(app.liveAxes,blue);
app.formantBoxes=gobjects(1,2);
for k=1:2
    x0=1010+(k-1)*206;
    uicontrol(app.figure,'Style','text','String',sprintf('F%d Hz',k),'Position',[x0 258 160 25], ...
        'FontName','Arial','FontSize',11,'BackgroundColor',ground,'HorizontalAlignment','left');
    app.formantBoxes(k)=uicontrol(app.figure,'Style','edit','String','','Tag',sprintf('F%d',k), ...
        'Position',[x0 217 160 37],'BackgroundColor','w','FontName','Arial','FontSize',13, ...
        'Callback',@(s,~) app.setFormant(k,str2double(s.String)));
end
app.cornerLabels=gobjects(1,4);
for k=1:4
    app.cornerLabels(k)=uicontrol(app.figure,'Style','togglebutton','String',num2str(k),'Tag',num2str(k), ...
        'Position',[18+(k-1)*235 30 217 62],'FontName','Arial','FontSize',11, ...
        'BackgroundColor',key,'Callback',@(~,~) app.setCorner(k));
end
app.writeKey=uicontrol(app.figure,'Style','pushbutton','String','WRITE BODY FILE','Tag','WRITE BODY FILE', ...
    'Position',[1010 45 360 42],'FontName','Arial','FontSize',11,'BackgroundColor',key, ...
    'Callback',@(~,~) app.writeBodyFile);
end
function name=referenceName(name)
name=erase(name,'vowel ');
words=strsplit(name);
if numel(words)>1, name=[words{1} '_{' strjoin(words(2:end),' ') '}']; end
end
