function build(app,visible)
blue=[0 114 189]/255; ground=[.8 .8 .8]; key=[226 226 226]/255;
app.figure=figure('Name','HEADSPACE','NumberTitle','off','MenuBar','none','ToolBar','none', ...
    'Visible',visible,'Color',ground,'Renderer','opengl','Theme','light','Position',[60 50 1480 860], ...
    'Resize','off','InvertHardcopy','off','CloseRequestFcn',@(~,~) delete(app), ...
    'WindowKeyPressFcn',@(~,e) app.onKey(e),'WindowButtonMotionFcn',@(~,~) app.onField('drag'), ...
    'WindowButtonUpFcn',@(~,~) app.onField('release'));
names={'PLAY','SAW','PINK NOISE'}; positions=[1010 790 90 32;1110 790 80 32;1200 790 170 32];
callbacks={@(s,~) app.setPlaying(logical(s.Value)),@(~,~) app.setSource('saw'),@(~,~) app.setSource('noise')};
app.keys=gobjects(1,3);
for k=1:3
    app.keys(k)=uicontrol(app.figure,'Style','togglebutton','String',names{k},'Tag',names{k},'Position',positions(k,:), ...
        'FontName','Arial','FontSize',11,'BackgroundColor',key,'Callback',callbacks{k});
end
panel=uipanel(app.figure,'Units','pixels','Position',[18 118 920 720],'BackgroundColor','w','BorderType','line');
app.fieldAxes=axes(panel,'Units','pixels','Position',[20 20 880 680],'Color','w', ...
    'XLim',[min(app.points(:,1)) max(app.points(:,1))],'YLim',[min(app.points(:,2)) max(app.points(:,2))], ...
    'YDir','reverse','DataAspectRatio',[1 1 1],'Visible','off','XTick',[],'YTick',[], ...
    'NextPlot','add','PositionConstraint','innerposition','ButtonDownFcn',@(~,~) app.onField('press'));
set(panel,'ButtonDownFcn',@(~,~) app.onField('press'));
panel=uipanel(app.figure,'Units','pixels','Position',[958 346 504 374],'BackgroundColor','w','BorderType','line');
app.liveAxes=trench.ui.draw.fixedGrid(panel,[49 40 432 288]);
app.liveCurve=trench.ui.draw.responseCurve(app.liveAxes,blue);
app.cornerLabels=gobjects(1,4);
for k=1:4
    app.cornerLabels(k)=uicontrol(app.figure,'Style','togglebutton','String',num2str(k),'Tag',num2str(k), ...
        'Position',[18+(k-1)*235 30 217 62],'FontName','Arial','FontSize',11, ...
        'BackgroundColor',key,'Callback',@(~,~) app.setCorner(k));
end
app.writeKey=uicontrol(app.figure,'Style','pushbutton','String','WRITE BODY FILE','Tag','WRITE BODY FILE', ...
    'Position',[1010 45 360 42],'FontName','Arial','FontSize',11,'BackgroundColor',key, ...
    'Callback',@(~,~) app.writeBodyFile);
end
